{% set version = "0.1.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cleanrmd
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/cleanrmd_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cleanrmd/cleanrmd_{{ version }}.tar.gz
  sha256: a6da62ccc183a77051967e633d52d8cb4b4aa8977cbf6d8b9ad75473277a1288

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-htmltools
    - r-jsonlite
    - r-rmarkdown
  run:
    - r-base
    - r-htmltools
    - r-jsonlite
    - r-rmarkdown

test:
  commands:
    - $R -e "library('cleanrmd')"           # [not win]
    - "\"%R%\" -e \"library('cleanrmd')\""  # [win]

about:
  home: https://pkg.garrickadenbuie.com/cleanrmd/, https://github.com/gadenbuie/cleanrmd
  license: MIT
  summary: A collection of clean 'R Markdown' HTML document templates using classy-looking classless CSS styles. These documents use a minimal set of dependencies but still look great, making them suitable for use a package vignettes or for sharing results via email.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
